### ISSUE TITLE
SWW vs SSW acronym

### ISSUE THREAD

**Issue by drsophiemurray** [TCDSolar/STELLAR_SSW_tutorials#7]
In the README file theres a few places that use stellar_ssw which is probably also throughout some of the code. This could be updated to stellar_sww for consistency with the webpage.

**Comment by drsophiemurray** [comment]
Actually I've just noticed its in the title too so maybe we just leave it as is! The age old problem of never getting SSW IDL out of our heads 😆

**Comment by hayesla** [comment]
yeah this is my bad - we've also named the environment `stellar_ssw` in the environment file - so people will have it named this on their local machines 🤦  

ssw keeps following us around ha!
